export const TRAVEL_STATUS = Object.freeze({
    PENDING: 'SUBMISSION PENDING',
    SUPERVISOR_REVIEW: 'SUPERVISOR REVIEW',
    PROCESSING: 'TRAVEL TEAM PROCESSING',
    AUTHORIZATIONS: 'HCA APPROVALS',
    TRAVEL_READY: 'TRAVEL READY',
    POST_TRAVEL_AWAITING: 'AWAITING FORM',
    COMPLETE: 'COMPLETE',
    DENIED: 'RETURNED / DENIED'
});